logging:
  level:
    root: info

spring:
  datasource:
    url: jdbc:mysql://123.206.72.106:3306/management?characterEncoding=utf-8
    username: admin
    password: 123456

mybatis:
  mapperLocations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true # 下划线转驼峰